sudo: false
language: python
python:
  - "2.7"
  - "3.6"
install:
  - "travis_retry pip install -U pip pytest pylint"
  - "travis_retry pip install .[test]"
  - "travis_retry pip install codecov"
script: "python setup.py test"
after_success:
  - "codecov"

matrix:
  include:
  - name: "Black"
    python: 3.6
    install: travis_retry pip install black
    script: black --check .
    after_success: skip
